#!/usr/bin/env bash
# iso/installer/build.sh — bakes Anaconda + the offline flatpak set + live-boot
# support into the throwaway installer image (see Containerfile in this dir).
#
# Runs INSIDE the installer image build (RUN'd from the Containerfile). Replaces
# svk's old iso/hook-anaconda.sh: upstream Titanoboa dropped its HOOK_post_rootfs
# mechanism and stopped shipping Anaconda entirely (container-native ISO contract
# v0.1.0 — see https://github.com/ondrejbudai/bootc-isos). Everything the ISO
# needs (installer, kickstart, pre-seeded flatpaks, dracut-live, iso.yaml) is now
# this image's own responsibility, same pattern ublue-os/bazzite uses in its
# installer/ directory.
#
# svk stays simple relative to bazzite's version: GNOME-only (no per-DE
# branching), no Secure Boot enrollment (N4 — no custom kmods on the raw
# Silverblue base), no multi-desktop/nvidia variants.
set -euxo pipefail

FLAVOR="${FLAVOR:?FLAVOR must be set (student|staff)}"
case "$FLAVOR" in student|staff) ;; *) echo "FLAVOR must be student|staff" >&2; exit 1 ;; esac

# The real registry ref the installed machine should track, e.g.
# ghcr.io/svkoulu/svk-student:stable — independent of what this installer image
# was built FROM (which may be a local dev tag). Baked into the kickstart's
# ostreecontainer + bootc switch targets.
: "${IMAGE_REF:?IMAGE_REF must be set (ghcr.io/svkoulu/svk-<flavor>:<tag>)}"
IMAGE_REPO="${IMAGE_REF%%:*}"
IMAGE_TAG="${IMAGE_REF##*:}"; [[ "$IMAGE_TAG" == "$IMAGE_REPO" ]] && IMAGE_TAG="stable"

# Temporary LUKS passphrase used only to create the encrypted disk during install.
# Generated fresh per ISO build (iso/build-iso.sh) and baked into the kickstart.
# It is written to the installed system as /etc/svk/luks-bootstrap so the first-boot
# svk-luks-tpm-enroll.service can authorise TPM2 + recovery-key enrollment, after
# which that same service WIPES this slot and deletes the file — so it never
# unlocks anything on the deployed fleet. See files/base/usr/libexec/svk/luks-tpm-enroll.
: "${LUKS_BOOTSTRAP_PASSPHRASE:?LUKS_BOOTSTRAP_PASSPHRASE must be set (generated by iso/build-iso.sh)}"

LABEL="SVK-$(tr '[:lower:]' '[:upper:]' <<<"${FLAVOR:0:1}")${FLAVOR:1}-Live"

### Live-environment tweaks ####################################################
# Don't suspend during install / first-boot user creation.
tee /usr/share/glib-2.0/schemas/zz3-svk-installer-power.gschema.override <<'EOF'
[org.gnome.settings-daemon.plugins.power]
sleep-inactive-ac-type='nothing'
sleep-inactive-battery-type='nothing'
sleep-inactive-ac-timeout=0
sleep-inactive-battery-timeout=0

[org.gnome.desktop.session]
idle-delay=uint32 0
EOF
glib-compile-schemas /usr/share/glib-2.0/schemas

# Services that should not run in the throwaway live environment.
for unit in rpm-ostree-countme.service tailscaled.service bootloader-update.service \
            rpm-ostreed-automatic.timer uupd.timer; do
    systemctl disable "$unit" 2>/dev/null || true
done

### Install Anaconda into the live ISO #########################################
dnf5 install -y \
    libblockdev-btrfs \
    libblockdev-lvm \
    libblockdev-dm \
    anaconda-live \
    firefox            # live-env browser only; not in the installed svk image

mkdir -p /var/lib/rpm-state # needed for Anaconda's WebUI front-end

# Anaconda profile for svk. Matches our os-release VARIANT_ID=silverblue (svk-base
# is raw Silverblue, not FROM bluefin, so it never gets bluefin's VARIANT_ID=main —
# confirmed by inspecting a built image; the old hook-anaconda.sh's "variant_id =
# main" was never validated and was simply wrong, so Anaconda fell back to a
# different, non-svk profile).
#
# No hidden_spokes/hidden_webui_pages here: the WebUI ignores the old GTK spoke
# names (that's why a hidden UserSpoke still showed the account page), and the
# modern anaconda-screen-* page ids are Fedora-version-fragile. Instead the
# kickstart below *pre-satisfies* every step (locale/keyboard/timezone/storage/
# encryption), so nothing prompts — and for staff it deliberately leaves the
# account undefined, making the Create Account page the single interactive step.
mkdir -p /etc/anaconda/profile.d
tee /etc/anaconda/profile.d/svk.conf <<'EOF'
[Profile]
profile_id = svk

[Profile Detection]
os_id = fedora
variant_id = silverblue

[Network]
default_on_boot = FIRST_WIRED_WITH_LINK

[Bootloader]
efi_dir = fedora
menu_auto_hide = True

[Storage]
default_scheme = BTRFS
btrfs_compression = zstd:1

[Localization]
use_geolocation = False
EOF

### Populate this image's own containers-storage with the install target #######
# `ostreecontainer --transport=containers-storage` (below) installs from a copy
# already sitting in local container storage — no network needed at install
# time. That copy has to be put there at BUILD time: building `FROM` the target
# image only gives this installer image the same filesystem content, not a
# separate, discretely-tagged image entry for Anaconda to find. Nested podman
# (enabled by --cap-add sys_admin on the outer `podman build`) pulls it in.
# Requires the ref to already be published and pullable (ghcr packages public,
# or credentials available) — matches Bazzite's installer/build.sh pattern.
#
# The nested pull inherits THIS filesystem's own strict /etc/containers/policy.json
# (cosign-signed-only for ghcr.io/svkoulu), which rejects it — sigstore-attachment
# discovery doesn't verify the same way from inside a nested build. Swap in a
# permissive policy just for this internal fetch: the kickstart's own install step
# already does `--no-signature-verification` explicitly, and the INSTALLED system's
# real policy.json comes from the deployed svk-staff content itself, not from
# anything in this throwaway installer image, so this has no effect on the fleet's
# actual signature enforcement.
cp /etc/containers/policy.json /tmp/svk-policy.json
echo '{"default":[{"type":"insecureAcceptAnything"}]}' > /etc/containers/policy.json
podman pull "${IMAGE_REPO}:${IMAGE_TAG}"
mv /tmp/svk-policy.json /etc/containers/policy.json

### Kickstart #################################################################
# The kickstart pre-satisfies every Anaconda step so nothing prompts: Finnish
# locale + keyboard, Helsinki timezone, and full-disk btrfs with LUKS encryption
# (TPM2 auto-unlock is enrolled at first boot — see luks-tpm-enroll in the base
# image). It installs the svk image from the ISO's own containers-storage, then
# re-points the bootc origin at the signed registry ref so the machine auto-updates
# from ghcr enforcing svk's cosign policy; disables Fedora flatpaks; rsyncs the
# offline-baked flatpaks onto the target; and fixes their SELinux labels. NO Secure
# Boot enrollment.
#
#   student — fully unattended: complete kickstart (baked opilas account, locked
#             root, reboot) delivered via inst.ks= on the boot cmdline (iso.yaml).
#   staff   — everything preset EXCEPT the account, appended to interactive-defaults.ks
#             so the WebUI's Create Account page is the single manual step.
mkdir -p /usr/share/anaconda/post-scripts

# Directives shared by both flavors. `clearpart --all` + `autopart` remove the disk
# prompt; `--encrypted --passphrase` creates the LUKS container with the temporary
# bootstrap passphrase (wiped at first boot). `--noswap`: rely on Silverblue's zram.
common_ks() {
cat <<EOF
# Localization — Finnish language + keyboard, Helsinki time.
lang fi_FI.UTF-8
keyboard --vckeymap=fi --xlayouts=fi
timezone Europe/Helsinki --utc

# Full disk, btrfs, LUKS. TPM2 is pre-enrolled at install time (svk-luks-tpm.ks
# %post, in the chroot) so the FIRST boot auto-unlocks with no passphrase prompt;
# the kernel arg tells the initramfs to try the TPM before falling back to a prompt.
zerombr
clearpart --all --initlabel
autopart --type=btrfs --noswap --encrypted --passphrase="${LUKS_BOOTSTRAP_PASSPHRASE}"
bootloader --append="rd.luks.options=tpm2-device=auto"

ostreecontainer --url=${IMAGE_REPO}:${IMAGE_TAG} --transport=containers-storage --no-signature-verification
%include /usr/share/anaconda/post-scripts/svk-configure-upgrade.ks
%include /usr/share/anaconda/post-scripts/svk-disable-fedora-flatpak.ks
%include /usr/share/anaconda/post-scripts/svk-install-flatpaks.ks
%include /usr/share/anaconda/post-scripts/svk-flatpak-selinux.ks
%include /usr/share/anaconda/post-scripts/svk-luks-bootstrap.ks
%include /usr/share/anaconda/post-scripts/svk-luks-tpm.ks
EOF
}

case "$FLAVOR" in
student)
    # Complete, non-interactive kickstart: no account page (opilas is baked into the
    # image via sysusers.d), root locked, auto-reboot when done. Referenced by
    # inst.ks= in iso.yaml so Anaconda runs it start-to-finish with no clicks.
    { common_ks; cat <<'EOF'
rootpw --lock
firstboot --disable
reboot
EOF
    } > /usr/share/anaconda/svk-student.ks
    ;;
staff)
    # Append to the default-loaded interactive kickstart. No user/rootpw line, so
    # the WebUI stops at Create Account — the one manual step (username + password).
    { common_ks; echo 'firstboot --disable'; } >> /usr/share/anaconda/interactive-defaults.ks
    ;;
esac

# Re-point the update source to the signed registry ref.
tee /usr/share/anaconda/post-scripts/svk-configure-upgrade.ks <<EOF
%post --erroronfail
bootc switch --mutate-in-place --enforce-container-sigpolicy --transport registry ${IMAGE_REPO}:${IMAGE_TAG}
%end
EOF

# Never ship the Fedora flatpak remote.
tee /usr/share/anaconda/post-scripts/svk-disable-fedora-flatpak.ks <<'EOF'
%post --erroronfail
systemctl disable flatpak-add-fedora-repos.service 2>/dev/null || true
%end
EOF

# Bake the offline flatpaks: rsync this installer image's own (pre-populated
# below) /var/lib/flatpak into the target deployment's /var/lib. This is the
# mechanism that makes first boot fully offline and puts the apps in system
# scope (so a student home-reset never loses them).
tee /usr/share/anaconda/post-scripts/svk-install-flatpaks.ks <<'EOF'
%post --erroronfail --nochroot
deployment="$(ostree rev-parse --repo=/mnt/sysimage/ostree/repo ostree/0/1/0)"
target="/mnt/sysimage/ostree/deploy/default/deploy/${deployment}.0/var/lib/"
mkdir -p "$target"
rsync -aAXUHKP --open-noatime /var/lib/flatpak "$target"
sync "$target"
%end
EOF

# Fix SELinux labels on the rsync'd flatpaks (rsync --nochroot doesn't relabel).
tee /usr/share/anaconda/post-scripts/svk-flatpak-selinux.ks <<'EOF'
%post --erroronfail
chcon -R -t var_lib_t /var/lib/flatpak
%end
EOF

# Stash the temporary LUKS bootstrap passphrase for the install-time + first-boot
# TPM enrollment. The first-boot service (files/base/usr/libexec/svk/luks-tpm-enroll)
# uses it to add the recovery key, then wipes this slot and deletes the file — so it
# never unlocks anything on the running fleet.
tee /usr/share/anaconda/post-scripts/svk-luks-bootstrap.ks <<EOF
%post --erroronfail
umask 077
mkdir -p /etc/svk
printf '%s\n' '${LUKS_BOOTSTRAP_PASSPHRASE}' > /etc/svk/luks-bootstrap
chmod 600 /etc/svk/luks-bootstrap
%end
EOF

# Pre-enroll the TPM2 in the chroot so the FIRST boot auto-unlocks (no passphrase
# prompt). Reads the passphrase from the file the previous %post wrote, so nothing
# has to be quoted/escaped here. Best-effort: a machine with no TPM (or a failed
# enrollment) just falls back to typing the bootstrap passphrase once + the
# first-boot service. PCR 7 (secure-boot state) is identical in the installer and
# the installed system on the same machine; PCRs 4/8/9 are NOT, so bind only PCR 7.
tee /usr/share/anaconda/post-scripts/svk-luks-tpm.ks <<'EOF'
%post --erroronfail
if { [ -e /dev/tpmrm0 ] || [ -e /dev/tpm0 ]; } && [ -f /etc/svk/luks-bootstrap ]; then
    _uuid="$(awk '!/^#/ && NF {print $2; exit}' /etc/crypttab | sed 's/^UUID=//')"
    _dev="/dev/disk/by-uuid/${_uuid}"
    if [ -n "$_uuid" ] && [ -e "$_dev" ]; then
        PASSWORD="$(cat /etc/svk/luks-bootstrap)" \
            systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=7 "$_dev" \
            || echo "svk: install-time TPM2 enrollment failed; first boot will retry."
    fi
fi
%end
EOF

### Bake the offline flatpak set into THIS image ###############################
curl --retry 3 -Lo /etc/flatpak/remotes.d/flathub.flatpakrepo https://dl.flathub.org/repo/flathub.flatpakrepo
cat /tmp/flatpaks/common.list "/tmp/flatpaks/${FLAVOR}.list" \
    | sed 's/#.*//' | tr -d '[:blank:]' | grep -v '^$' | sort -u \
    | xargs -r flatpak install -y --noninteractive --system flathub

### Live-boot support (dracut-live: dmsquash-live mounts the squashfs at boot) ##
dnf5 install -y dracut-live
kernel="$(find /usr/lib/modules -mindepth 1 -maxdepth 1 -type d -printf '%P\n' | head -1)"
DRACUT_NO_XATTR=1 dracut -v --force --zstd --reproducible --no-hostonly \
    --add "dmsquash-live dmsquash-live-autooverlay" \
    "/usr/lib/modules/${kernel}/initramfs.img" "${kernel}"

### Live session (GNOME auto-login so there's a desktop to launch Anaconda from) #
dnf5 install -y livesys-scripts
sed -i "s/^livesys_session=.*/livesys_session=gnome/" /etc/sysconfig/livesys
systemctl enable livesys.service livesys-late.service

### EFI directory (container-native contract expects /boot/efi/EFI/$VENDOR) ####
dnf5 install -y grub2-efi-x64-cdboot
mkdir -p /boot/efi
cp -av /usr/lib/efi/*/*/EFI /boot/efi/

### Live-root runtime mounts ####################################################
# ostree needs real /var/tmp space; the live root's overlayfs-backed /var/tmp
# otherwise lives under the small tmpfs at /run.
tee /etc/systemd/system/var-tmp.mount <<'EOF'
[Unit]
Description=Larger tmpfs for /var/tmp on the live system

[Mount]
What=tmpfs
Where=/var/tmp
Type=tmpfs
Options=size=50%,nr_inodes=1m

[Install]
WantedBy=local-fs.target
EOF
systemctl enable var-tmp.mount

# Keep the baked flatpaks read-only while live, so they can't get corrupted
# before the install-time rsync copies them onto the target.
tee /etc/systemd/system/var-lib-flatpak.mount <<'EOF'
[Mount]
Type=none
What=/var/lib/flatpak
Where=/var/lib/flatpak
Options=bind,ro

[Install]
WantedBy=multi-user.target
EOF
systemctl enable var-lib-flatpak.mount

### Titanoboa contract: /usr/lib/bootc-image-builder/iso.yaml ##################
# student boots straight into the complete kickstart (inst.ks=) for a zero-click
# install; staff omits it so Anaconda loads the default interactive-defaults.ks and
# stops only at the Create Account page.
KS_ARG=""
[[ "$FLAVOR" == "student" ]] && KS_ARG=" inst.ks=file:///usr/share/anaconda/svk-student.ks"

mkdir -p /usr/lib/bootc-image-builder
tee /usr/lib/bootc-image-builder/iso.yaml <<EOF
label: "${LABEL}"
grub2:
  timeout: 10
  default: 0
  entries:
    - name: "Install SVK ${FLAVOR^}"
      linux: "/images/pxeboot/vmlinuz quiet rhgb root=live:CDLABEL=${LABEL} enforcing=0 rd.live.image${KS_ARG}"
      initrd: "/images/pxeboot/initrd.img"
    - name: "Install SVK ${FLAVOR^} (Basic Graphics Mode)"
      linux: "/images/pxeboot/vmlinuz quiet rhgb root=live:CDLABEL=${LABEL} enforcing=0 rd.live.image nomodeset${KS_ARG}"
      initrd: "/images/pxeboot/initrd.img"
EOF

dnf5 clean all

echo "svk installer build.sh complete for ${IMAGE_REPO}:${IMAGE_TAG} (${FLAVOR})"
